[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && gunicorn crowdcontrol.wsgi"
healthcheckPath = "/api/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
